name: Generate RSS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Generate RSS
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Generate RSS file
        run: |
          python cmd/rss_grenerator.py
      
